import { NextRequest, NextResponse } from 'next/server'
import { parse } from 'csv-parse/sync'
import { StandardCsvAdapter } from '@/lib/admin/adapters/standard-csv'
import { buildInvoiceKey, isR2Configured, pdfExistsOnR2, uploadPdfToR2 } from '@/lib/r2'
import { requireAdmin } from '@/lib/auth-checks'
import { createAdminClient } from '@/lib/supabase/admin'

// Simple in-memory rate limiting map (Admin specific)
const uploadRateLimit = new Map<string, { count: number, lastReset: number }>()
const RATE_LIMIT_WINDOW = 10 * 60 * 1000 // 10 minutes
const MAX_UPLOADS_PER_WINDOW = 5

export async function POST(req: NextRequest) {
    // Service-role client, per request (admin-gated below) — never a module singleton.
    const supabase = createAdminClient()
    try {
        const authCheck = await requireAdmin()
        if (authCheck.error) {
            return NextResponse.json({ error: authCheck.error }, { status: authCheck.status })
        }

        // 0. Basic Rate Limiting check (per Admin user)
        const userId = authCheck.user?.id
        if (userId) {
            const now = Date.now()
            const userLimit = uploadRateLimit.get(userId) || { count: 0, lastReset: now }

            if (now - userLimit.lastReset > RATE_LIMIT_WINDOW) {
                userLimit.count = 0
                userLimit.lastReset = now
            }

            if (userLimit.count >= MAX_UPLOADS_PER_WINDOW) {
                return NextResponse.json({
                    error: 'Troppi tentativi di upload rilevati. Per sicurezza, attendi 10 minuti prima del prossimo invio.'
                }, { status: 429 })
            }

            userLimit.count++
            uploadRateLimit.set(userId, userLimit)
        }

        const formData = await req.formData()
        const file = formData.get('csv') as File
        const importId = formData.get('importId') as string // Client generated ID

        // Progress Tracking Helpers
        let totalFiles = 0
        let processedTotal = 0
        let lastUpdate = 0

        const updateProgress = async (current: string, processed: number, total: number, status: 'processing' | 'completed' | 'error' = 'processing') => {
            console.log(`[Upload API] updateProgress called for ID: ${importId} with status: ${status}`)
            const now = Date.now()
            // Update at most once per second or if completed/error
            if (importId && (now - lastUpdate > 1000 || status !== 'processing')) {
                lastUpdate = now
                const { error: logError } = await supabase
                    .from('import_logs')
                    .upsert(
                        {
                            status: status,
                            current_file: current,
                            processed_files: processed,
                            total_files: total,
                            archive_name: formData.get('archive') ? (formData.get('archive') as File).name : null,
                            r2_path: importId,
                        },
                        { onConflict: 'r2_path' }
                    )
                if (logError) {
                    console.error(`[Upload API] Log update failed for ${importId}:`, logError)
                }
            }
        }

        // Initialize Log (r2_path is the idempotency key; id is auto-generated by DB).
        if (importId) {
            console.log(`[Upload API] Initializing log for r2_path: ${importId}`)
            const { error: logInitError } = await supabase
                .from('import_logs')
                .upsert(
                    {
                        status: 'processing',
                        total_files: totalFiles,
                        processed_files: 0,
                        current_file: 'Analisi CSV...',
                        r2_path: importId,
                    },
                    { onConflict: 'r2_path' }
                )
            if (logInitError) {
                console.error('[Upload API] Failed to initialize import log:', logInitError)
            }
        } else {
            console.warn('[Upload API] No importId provided, skipping log initialization')
        }

        // Initial log initialized above

        // 1. Fetch Existing Profiles (Batched)
        const allProfiles: any[] = []
        let hasMore = true
        let page = 0
        const pageSize = 1000

        try {
            while (hasMore) {
                const { data, error } = await supabase
                    .from('profiles')
                    .select('id, codice_cliente')
                    .range(page * pageSize, (page + 1) * pageSize - 1)

                if (error) throw error

                if (data) {
                    allProfiles.push(...data)
                    if (data.length < pageSize) hasMore = false
                    else page++
                } else {
                    hasMore = false
                }
            }
        } catch (profileError) {
            console.error('Profile Fetch Error:', profileError)
            return NextResponse.json({ error: 'Database error fetching profiles' }, { status: 500 })
        }

        const clientCodeMap = new Map<string, string>()

        allProfiles.forEach(p => {
            if (p.codice_cliente) clientCodeMap.set(p.codice_cliente.trim(), p.id)
        })

        console.log(`[Upload] Loaded ${allProfiles.length} profiles from DB for deduplication.`)

        // 2. PARSE via Adapter
        const adapter = new StandardCsvAdapter()
        await updateProgress('Analisi del file in corso...', 0, 0)

        const text = await file.text()
        const { bills: parsedBills, errors: parseErrors } = await adapter.parse(text)

        // 3. DUPLICATE BILL CHECK (Check for idboll already in bills table)
        const allDocNumbers = parsedBills
            .map(b => (b as any).idboll as number | null)
            .filter((n): n is number => typeof n === 'number' && n > 0)
        const existingNumbers = new Set<number>()

        if (allDocNumbers.length > 0) {
            const chunkSize = 1000
            for (let i = 0; i < allDocNumbers.length; i += chunkSize) {
                const chunk = allDocNumbers.slice(i, i + chunkSize)
                const { data: existing } = await supabase
                    .from('bills')
                    .select('idboll')
                    .in('idboll', chunk)

                if (existing) {
                    existing.forEach(row => {
                        if (typeof row.idboll === 'number') existingNumbers.add(row.idboll)
                    })
                }
            }
        }

        // In-batch dedup so the same CSV cannot violate the UNIQUE index on idboll.
        const seenInBatch = new Set<number>()
        const billsToInsert = parsedBills.filter(b => {
            const k = (b as any).idboll as number | null
            if (typeof k === 'number' && k > 0) {
                if (existingNumbers.has(k) || seenInBatch.has(k)) return false
                seenInBatch.add(k)
            }
            return true
        })
        const duplicateBillCount = parsedBills.length - billsToInsert.length
        
        console.log(`[Upload] Parsed ${parsedBills.length} total. Duplicates: ${duplicateBillCount}. New to insert: ${billsToInsert.length}`)

        // Update stats
        totalFiles = billsToInsert.length
        let processedBills = billsToInsert.length
        let newProfiles = 0
        const errors: string[] = []
        errors.push(...parseErrors)

        const matchedCifIds = new Set<string>()
        const matchedCfpiIds = new Set<string>()

        // Reconstruct stats for the response
        // Link Users via Client Code
        billsToInsert.forEach(b => {
            if (b.codice_cliente && clientCodeMap.has(b.codice_cliente)) {
                b.user_id = clientCodeMap.get(b.codice_cliente)!
                matchedCifIds.add(b.user_id) // Reusing set name for stats simplification
            }
        })

        if (parseErrors.length > 0) {
            await updateProgress(`Rilevati ${parseErrors.length} errori nel parsing`, totalFiles, totalFiles)
        }

        const previewMode = req.nextUrl.searchParams.get('preview') === 'true'
        const forceUpload = req.nextUrl.searchParams.get('force') === 'true'

        if (!previewMode) {
            const chunkSize = 500
            for (let i = 0; i < billsToInsert.length; i += chunkSize) {
                const chunk = billsToInsert.slice(i, i + chunkSize).map(({ original_row_index, ...rest }) => ({
                    ...rest,
                    import_log_id: importId || null,
                }))
                // `id` is auto-generated (identity); we rely on idboll UNIQUE for integrity.
                const { error: insertError } = await supabase.from('bills').insert(chunk)
                if (insertError) {
                    console.error('Bill Insert Error:', insertError.message)
                    errors.push(`Batch ${i}: ${insertError.message}`)
                }
                processedTotal += chunk.length
                await updateProgress(`Salvataggio dati ${Math.min(processedTotal, totalFiles)}/${billsToInsert.length}...`, processedTotal, totalFiles)
            }
        }

        const archiveFile = formData.get('archive') as File
        let pdfsUploaded = 0
        let pdfsSkipped = 0
        let pdfsLinked = 0
        let previewPdfCount = 0
        let previewPdfMatches = 0
        let previewAlreadyLinked = 0

        let duplicateArchive = false
        let existingArchiveTotal = 0
        let overwriteWarning = false

        if (archiveFile) {
            // Check for duplicates
            const { data: existingLogs } = await supabase
                .from('import_logs')
                .select('total_files')
                .eq('archive_name', archiveFile.name)
                .eq('status', 'completed')
                .order('created_at', { ascending: false })
                .limit(1)

            if (existingLogs && existingLogs.length > 0) {
                duplicateArchive = true
                existingArchiveTotal = existingLogs[0].total_files
                if (previewMode && !forceUpload) {
                    // Return immediately with warning info so frontend can prompt user
                    // But we continue to get stats if possible?
                    // Actually, in preview mode we want to show the stats BUT warn about the duplicate.
                    // We will add these flags to the JSON response.
                }
            }

            try {
                await updateProgress('Estrazione archivio...', processedTotal, totalFiles)
                const fs = require('fs')
                const path = require('path')
                const no7z = require('node-7z')
                const sevenBin = require('7zip-bin')
                let pathTo7zip = sevenBin.path7za

                if (!fs.existsSync(pathTo7zip)) {
                    const manualPath = path.join(/*turbopackIgnore: true*/ process.cwd(), 'node_modules', '7zip-bin', 'win', 'x64', '7za.exe')
                    if (fs.existsSync(manualPath)) {
                        pathTo7zip = manualPath
                    } else {
                        const manualPathUp = path.join(/*turbopackIgnore: true*/ process.cwd(), '..', 'node_modules', '7zip-bin', 'win', 'x64', '7za.exe')
                        if (fs.existsSync(manualPathUp)) pathTo7zip = manualPathUp
                    }
                }

                const tempDir = path.join(/*turbopackIgnore: true*/ process.cwd(), 'tmp')
                if (!fs.existsSync(tempDir)) fs.mkdirSync(tempDir)

                // Use original filename to prevent duplicates in tmp folder as per user request
                const originalName = archiveFile.name
                const safeName = originalName.replace(/[^a-z0-9.]/gi, '_') // Basic sanitization
                const archivePath = path.join(tempDir, safeName)
                const extractPath = path.join(tempDir, `extract_${safeName.replace(/\./g, '_')}`)

                const buffer = Buffer.from(await archiveFile.arrayBuffer())
                fs.writeFileSync(archivePath, buffer)

                interface SevenZipError extends Error {
                    stderr?: string;
                }

                const pdfFiles: string[] = []

                if (previewMode) {
                    const stream = no7z.list(archivePath, {
                        $bin: pathTo7zip,
                        recursive: true
                    })

                    await new Promise<void>((resolve, reject) => {
                        stream.on('data', (file: any) => {
                            if (file.file && file.file.toLowerCase().endsWith('.pdf')) {
                                pdfFiles.push(file.file)
                            }
                        })
                        stream.on('end', () => resolve())
                        stream.on('error', (err: SevenZipError) => reject(err))
                    })

                    // CHECK DUPLICATES IN PREVIEW
                    const pdfNames = pdfFiles.map(p => path.basename(p))
                    const matchSet = new Set<string>()
                    const alreadyLinkedSet = new Set<string>()

                    // 1. Check against CSV Data (In-Memory)
                    const csvPdfSet = new Set(billsToInsert.map(b => b.nome_pdf.toLowerCase()))

                    // 2. Check against DB - Fetch ALL linked bills for robust case-insensitive check
                    const dbBills: any[] = []
                    let billsHasMore = true
                    let billsPage = 0
                    const billsPageSize = 2500 // Large pages for efficiency

                    while (billsHasMore) {
                        const { data, error } = await supabase
                            .from('bills')
                            .select('nome_pdf, pdf_url')
                            .not('nome_pdf', 'is', null)
                            .range(billsPage * billsPageSize, (billsPage + 1) * billsPageSize - 1)

                        if (error) {
                            console.error('Error fetching bills for preview:', error)
                            billsHasMore = false
                        } else if (data) {
                            dbBills.push(...data)
                            if (data.length < billsPageSize) billsHasMore = false
                            else billsPage++
                        } else {
                            billsHasMore = false
                        }
                    }

                    // Let's simplify: Build a Map from DB
                    const dbMap = new Map<string, string>() // filename -> url
                    dbBills.forEach(d => {
                        if (d.nome_pdf) dbMap.set(d.nome_pdf.toLowerCase(), d.pdf_url || '')
                    })

                    // Now iterate the ZIP files
                    pdfNames.forEach(name => {
                        const lowerName = name.toLowerCase()
                        if (dbMap.has(lowerName)) {
                            matchSet.add(lowerName)
                            const url = dbMap.get(lowerName)
                            if (url && url.startsWith('/invoices/')) {
                                alreadyLinkedSet.add(lowerName)
                            }
                        }
                    })

                    // Add CSV matches to matchSet
                    pdfNames.forEach(name => {
                        if (csvPdfSet.has(name.toLowerCase())) {
                            matchSet.add(name.toLowerCase())
                        }
                    })

                    pdfsSkipped = alreadyLinkedSet.size
                    previewAlreadyLinked = alreadyLinkedSet.size
                    previewPdfMatches = matchSet.size // Total found in DB OR CSV
                    previewPdfCount = pdfFiles.length
                } else {
                    // 1. Extract Archive
                    await new Promise<void>((resolve, reject) => {
                        const stream = no7z.extractFull(archivePath, extractPath, {
                            $bin: pathTo7zip,
                            recursive: true
                        })
                        stream.on('end', () => resolve())
                        stream.on('error', (err: SevenZipError) => reject(err))
                    })

                    const getAllFiles = (dir: string, fileList: string[] = []) => {
                        if (!fs.existsSync(dir)) return fileList
                        const files = fs.readdirSync(dir)
                        files.forEach((file: string) => {
                            const filePath = path.join(dir, file)
                            if (fs.statSync(filePath).isDirectory()) {
                                getAllFiles(filePath, fileList)
                            } else {
                                fileList.push(filePath)
                            }
                        })
                        return fileList
                    }

                    const extracted = getAllFiles(extractPath)
                    pdfFiles.push(...extracted.filter(f => f.toLowerCase().endsWith('.pdf')))

                    // Update total to include PDF files
                    // RESET counts for PDF phase to make it clearer for the user (0 to N instead of N to N+M)
                    totalFiles = pdfFiles.length
                    processedTotal = 0
                    await updateProgress('Analisi PDF estratti...', 0, totalFiles)

                    // 2. Filter Duplicates (Check DB) & Storage
                    const pdfNames = pdfFiles.map(p => path.basename(p))
                    const existingPdfMap = new Map<string, string>()

                    // A. Check DB - Fetch ALL linked bills to handle case-insensitivity properly
                    const allBills: any[] = []
                    let bHasMore = true
                    let bPage = 0
                    const bPageSize = 2500

                    while (bHasMore) {
                        const { data, error } = await supabase
                            .from('bills')
                            .select('nome_pdf, pdf_url')
                            .not('nome_pdf', 'is', null)
                            .range(bPage * bPageSize, (bPage + 1) * bPageSize - 1)

                        if (error) {
                            console.error('Error fetching all bills:', error)
                            bHasMore = false
                        } else if (data) {
                            allBills.push(...data)
                            if (data.length < bPageSize) bHasMore = false
                            else bPage++
                        } else {
                            bHasMore = false
                        }
                    }

                    allBills.forEach(d => {
                        if (d.nome_pdf) {
                            existingPdfMap.set(d.nome_pdf.toLowerCase(), d.pdf_url || '')
                        }
                    })

                    // B. Storage backend: prefer Cloudflare R2; fall back to local FS only if unconfigured.
                    const storageSubDir = 'invoices/acq'
                    const useR2 = isR2Configured()
                    const localInvoicesDir = path.join(/*turbopackIgnore: true*/ process.cwd(), 'public', storageSubDir)
                    if (!useR2 && !fs.existsSync(localInvoicesDir)) {
                        fs.mkdirSync(localInvoicesDir, { recursive: true })
                    }



                    console.log(`[Upload] Found ${existingPdfMap.size} bills already linked in DB.`)

                    // 3. Upload Non-Duplicates in Parallel
                    // Local FS is fast, but let's keep concurrency controlled to avoid blocking event loop too much
                    const CONCURRENCY = 10
                    for (let i = 0; i < pdfFiles.length; i += CONCURRENCY) {
                        if (req.signal.aborted) throw new Error('Upload aborted by user')

                        const chunk = pdfFiles.slice(i, i + CONCURRENCY)
                        await Promise.all(chunk.map(async (filePath) => {
                            processedTotal++
                            const rawName = path.basename(filePath)
                            // Hard sanitize: allow only safe chars, collapse others to underscore.
                            const filename = rawName.replace(/[^A-Za-z0-9._\- ]/g, '_')
                            if (!filename || filename.startsWith('.') || filename.length > 200) {
                                errors.push(`Skipped unsafe filename: ${rawName}`)
                                return
                            }
                            const lowerFilename = filename.toLowerCase()

                            // Check DB first — pdf_url now stores an R2 object key like "invoices/acq/<name>".
                            const existingUrl = existingPdfMap.get(lowerFilename)
                            if (existingUrl && (existingUrl.startsWith('invoices/') || existingUrl.startsWith('/invoices/'))) {
                                pdfsSkipped++
                                if (processedTotal % 50 === 0) {
                                    await updateProgress(`Skipped (Already Linked): ${filename}`, processedTotal, totalFiles)
                                }
                                return
                            }

                            const r2Key = buildInvoiceKey(filename, importId)
                            let needsUpload = true

                            try {
                                if (useR2) {
                                    if (await pdfExistsOnR2(r2Key)) {
                                        needsUpload = false
                                    }
                                    if (needsUpload) {
                                        const fileBuffer = fs.readFileSync(filePath)
                                        await uploadPdfToR2(r2Key, fileBuffer)
                                        pdfsUploaded++
                                    }
                                    if (processedTotal % 10 === 0) {
                                        await updateProgress(`R2: ${filename}`, processedTotal, totalFiles)
                                    }
                                } else {
                                    const targetPath = path.resolve(localInvoicesDir, filename)
                                    const invoicesRoot = path.resolve(localInvoicesDir) + path.sep
                                    if (!targetPath.startsWith(invoicesRoot)) {
                                        errors.push(`Skipped path traversal attempt: ${rawName}`)
                                        return
                                    }
                                    if (fs.existsSync(targetPath)) {
                                        needsUpload = false
                                    } else {
                                        const fileBuffer = fs.readFileSync(filePath)
                                        fs.writeFileSync(targetPath, fileBuffer)
                                        pdfsUploaded++
                                    }
                                }

                                // Persist the canonical object key in bills.pdf_url.
                                const persistedUrl = r2Key

                                const { error: updateError, data: updatedData } = await supabase
                                    .from('bills')
                                    .update({ pdf_url: persistedUrl })
                                    .ilike('nome_pdf', filename) // case-insensitive link
                                    .select('id')

                                if (updateError) {
                                    console.error(`DB Update Error for ${filename}:`, updateError)
                                } else {
                                    // console.log(`DB Update Success for ${filename}:`, updatedData)
                                }

                                if (!updateError && updatedData && updatedData.length > 0) {
                                    pdfsLinked++
                                } else {
                                    console.warn(`No DB match found for PDF to link: ${filename}`)
                                }

                            } catch (err) {
                                console.error(`File Processing Error: ${filePath}`, err)
                                errors.push(`Error ${filename}: ${err}`)
                            }
                        }))
                    }
                }

            } catch (err: any) {
                console.error('Archive Error', err)
                errors.push(`Archive Error: ${err.message}`)
            } finally {
                // Unified Cleanup in finally block
                try {
                    const fs = require('fs')
                    const path = require('path')
                    const originalName = archiveFile.name
                    const safeName = originalName.replace(/[^a-z0-9.]/gi, '_')
                    const archivePath = path.join(/*turbopackIgnore: true*/ process.cwd(), 'tmp', safeName)
                    const extractPath = path.join(/*turbopackIgnore: true*/ process.cwd(), 'tmp', `extract_${safeName.replace(/\./g, '_')}`)

                    if (fs.existsSync(archivePath)) {
                        fs.unlinkSync(archivePath)
                        console.log(`[Upload] Deleted temp archive: ${archivePath}`)
                    }
                    if (fs.existsSync(extractPath)) {
                        fs.rmSync(extractPath, { recursive: true, force: true })
                        console.log(`[Upload] Deleted extraction folder: ${extractPath}`)
                    }
                } catch (cleanupErr) {
                    console.error('[Upload] Cleanup failed:', cleanupErr)
                }
            }
        }

        const uniqueMatchedUsers = new Set([...matchedCifIds, ...matchedCfpiIds]).size

        // Final Completion Log
        if (importId) {
            await updateProgress('Completato', processedTotal, totalFiles, 'completed')
        }

        return NextResponse.json({
            success: true,
            preview: previewMode,
            processed: processedTotal,
            newUsers: newProfiles,
            matchedByCif: matchedCifIds.size,
            matchedByCfpi: 0,
            uniqueMatchedUsers,
            pdfsUploaded,
            pdfsSkipped,
            pdfsLinked,
            previewPdfCount,
            previewPdfMatches,
            previewAlreadyLinked: previewAlreadyLinked,
            duplicateBillCount, // New
            errors: errors,
            duplicateArchive,
            existingArchiveTotal,
            overwriteWarning: duplicateArchive // If duplicate, it's an overwrite warning
        })
    } catch (unexpectedError: any) {
        console.error('[Upload API] Critical Error:', unexpectedError?.message || unexpectedError)
        
        // Update log to error status if importId exists
        const importId = req.nextUrl.searchParams.get('importId') || 'unknown'
        try {
            await supabase.from('import_logs').update({
                status: 'error',
                current_file: `Errore Critico: ${unexpectedError?.message || 'Sconosciuto'}`
            }).eq('r2_path', importId)
        } catch (logErr) {
            console.error('Failed to update error status in log:', logErr)
        }

        return NextResponse.json({
            error: 'An unexpected error occurred during upload'
        }, { status: 500 })
    }
}
