import { NextRequest, NextResponse } from 'next/server'
import { StandardCsvAdapter } from '@/lib/admin/adapters/standard-csv'
import { requireAdmin } from '@/lib/auth-checks'
import { createAdminClient } from '@/lib/supabase/admin'
import { createImportProgress } from '@/lib/admin/import-progress'
import { loadProfileCodeMap } from '@/lib/admin/import/profiles'
import { partitionNewBills } from '@/lib/admin/import/dedup'
import { processArchive } from '@/lib/admin/import/archive'

// Simple in-memory rate limiting map (Admin specific)
const uploadRateLimit = new Map<string, { count: number, lastReset: number }>()
const RATE_LIMIT_WINDOW = 10 * 60 * 1000 // 10 minutes
const MAX_UPLOADS_PER_WINDOW = 5

export async function POST(req: NextRequest) {
    // Service-role client, per request (admin-gated below) — never a module singleton.
    const supabase = createAdminClient()
    try {
        const authCheck = await requireAdmin()
        if (authCheck.error) {
            return NextResponse.json({ error: authCheck.error }, { status: authCheck.status })
        }

        // 0. Basic Rate Limiting check (per Admin user)
        const userId = authCheck.user?.id
        if (userId) {
            const now = Date.now()
            const userLimit = uploadRateLimit.get(userId) || { count: 0, lastReset: now }

            if (now - userLimit.lastReset > RATE_LIMIT_WINDOW) {
                userLimit.count = 0
                userLimit.lastReset = now
            }

            if (userLimit.count >= MAX_UPLOADS_PER_WINDOW) {
                return NextResponse.json({
                    error: 'Troppi tentativi di upload rilevati. Per sicurezza, attendi 10 minuti prima del prossimo invio.'
                }, { status: 429 })
            }

            userLimit.count++
            uploadRateLimit.set(userId, userLimit)
        }

        const formData = await req.formData()
        const file = formData.get('csv') as File
        const importId = formData.get('importId') as string // Client generated ID
        const archiveFile = formData.get('archive') as File

        const progress = createImportProgress(supabase, importId, {
            archiveName: archiveFile ? archiveFile.name : null,
        })

        // Initialize Log (r2_path is the idempotency key; id is auto-generated by DB).
        if (importId) {
            await progress.init(0, 'Analisi CSV...')
        } else {
            console.warn('[Upload API] No importId provided, skipping log initialization')
        }

        // 1. Fetch existing profiles → codice_cliente map (for owner linking)
        let clientCodeMap: Map<string, string>
        try {
            clientCodeMap = await loadProfileCodeMap(supabase)
        } catch (profileError) {
            console.error('Profile Fetch Error:', profileError)
            return NextResponse.json({ error: 'Database error fetching profiles' }, { status: 500 })
        }
        console.log(`[Upload] Loaded ${clientCodeMap.size} profiles from DB for deduplication.`)

        // 2. PARSE via Adapter
        const adapter = new StandardCsvAdapter()
        await progress.update('Analisi del file in corso...', 0, 0)
        const text = await file.text()
        const { bills: parsedBills, errors: parseErrors } = await adapter.parse(text)

        // 3. DUPLICATE BILL CHECK (idboll already in bills, or repeated in batch)
        const { billsToInsert, duplicateBillCount } = await partitionNewBills(supabase, parsedBills)
        console.log(`[Upload] Parsed ${parsedBills.length} total. Duplicates: ${duplicateBillCount}. New to insert: ${billsToInsert.length}`)

        let totalFiles = billsToInsert.length
        let processedTotal = 0
        const newProfiles = 0
        const errors: string[] = [...parseErrors]
        const matchedCifIds = new Set<string>()

        // Link bills to their owner via Codice Cliente.
        billsToInsert.forEach(b => {
            if (b.codice_cliente && clientCodeMap.has(b.codice_cliente)) {
                b.user_id = clientCodeMap.get(b.codice_cliente)!
                matchedCifIds.add(b.user_id)
            }
        })

        if (parseErrors.length > 0) {
            await progress.update(`Rilevati ${parseErrors.length} errori nel parsing`, totalFiles, totalFiles)
        }

        const previewMode = req.nextUrl.searchParams.get('preview') === 'true'

        // 4. INSERT new bills (skipped in preview)
        if (!previewMode) {
            const chunkSize = 500
            for (let i = 0; i < billsToInsert.length; i += chunkSize) {
                const chunk = billsToInsert.slice(i, i + chunkSize).map(({ original_row_index, ...rest }) => ({
                    ...rest,
                    import_log_id: importId || null,
                }))
                // `id` is auto-generated (identity); we rely on idboll UNIQUE for integrity.
                const { error: insertError } = await supabase.from('bills').insert(chunk)
                if (insertError) {
                    console.error('Bill Insert Error:', insertError.message)
                    errors.push(`Batch ${i}: ${insertError.message}`)
                }
                processedTotal += chunk.length
                await progress.update(`Salvataggio dati ${Math.min(processedTotal, totalFiles)}/${billsToInsert.length}...`, processedTotal, totalFiles)
            }
        }

        // 5. ARCHIVE STAGE — extract PDFs and link/upload them
        let pdfsUploaded = 0
        let pdfsSkipped = 0
        let pdfsLinked = 0
        let previewPdfCount = 0
        let previewPdfMatches = 0
        let previewAlreadyLinked = 0
        let duplicateArchive = false
        let existingArchiveTotal = 0

        if (archiveFile) {
            const result = await processArchive({
                supabase, archiveFile, billsToInsert, importId,
                previewMode, abortSignal: req.signal, progress, errors,
                processedTotal, totalFiles,
            })
            pdfsUploaded = result.pdfsUploaded
            pdfsSkipped = result.pdfsSkipped
            pdfsLinked = result.pdfsLinked
            previewPdfCount = result.previewPdfCount
            previewPdfMatches = result.previewPdfMatches
            previewAlreadyLinked = result.previewAlreadyLinked
            duplicateArchive = result.duplicateArchive
            existingArchiveTotal = result.existingArchiveTotal
            processedTotal = result.processedTotal
            totalFiles = result.totalFiles
        }

        const uniqueMatchedUsers = matchedCifIds.size

        // Final Completion Log
        if (importId) {
            await progress.update('Completato', processedTotal, totalFiles, 'completed')
        }

        return NextResponse.json({
            success: true,
            preview: previewMode,
            processed: processedTotal,
            newUsers: newProfiles,
            matchedByCif: matchedCifIds.size,
            matchedByCfpi: 0,
            uniqueMatchedUsers,
            pdfsUploaded,
            pdfsSkipped,
            pdfsLinked,
            previewPdfCount,
            previewPdfMatches,
            previewAlreadyLinked,
            duplicateBillCount,
            errors,
            duplicateArchive,
            existingArchiveTotal,
            overwriteWarning: duplicateArchive, // If duplicate, it's an overwrite warning
        })
    } catch (unexpectedError: any) {
        console.error('[Upload API] Critical Error:', unexpectedError?.message || unexpectedError)

        // Update log to error status if importId exists
        const importId = req.nextUrl.searchParams.get('importId') || 'unknown'
        try {
            await supabase.from('import_logs').update({
                status: 'error',
                current_file: `Errore Critico: ${unexpectedError?.message || 'Sconosciuto'}`
            }).eq('r2_path', importId)
        } catch (logErr) {
            console.error('Failed to update error status in log:', logErr)
        }

        return NextResponse.json({
            error: 'An unexpected error occurred during upload'
        }, { status: 500 })
    }
}
