-- Migration: ensure bills.id is auto-generated identity and introduce "idBoll" (numero bolletta).
-- Idempotent: safe to re-run. Requires the table to be empty only when id needs to be converted.

-- 1. Convert bills.id to GENERATED BY DEFAULT AS IDENTITY (only if not already).
do $$
declare
  v_identity char(1);
begin
  select attidentity into v_identity
  from pg_attribute a
  join pg_class c on c.oid = a.attrelid
  where c.relname = 'bills' and a.attname = 'id' and a.attnum > 0;

  if v_identity is null or v_identity = '' then
    if exists (select 1 from public.bills limit 1) then
      raise exception 'public.bills is not empty — cannot convert id to identity without data migration';
    end if;
    -- Ensure no default interferes, then add identity.
    execute 'alter table public.bills alter column id drop default';
    execute 'alter table public.bills alter column id set not null';
    execute 'alter table public.bills alter column id add generated by default as identity';
  end if;
end $$;

-- 2. Add "idBoll" (quoted → preserves camelCase to match the JS client).
alter table public.bills
    add column if not exists "idBoll" integer;

-- 3. Unique index on idBoll (only when present).
create unique index if not exists bills_idboll_unique
    on public.bills ("idBoll")
    where "idBoll" is not null;

-- 4. Useful lookup indexes.
create index if not exists bills_user_id_idx on public.bills (user_id);
create index if not exists bills_codice_cliente_idx on public.bills (codice_cliente);

-- 5. Drop retired legacy columns (safe on empty table; ignore if columns don't exist).
alter table public.bills drop column if exists legacy_id;
alter table public.bills drop column if exists legacy_user_id;
